run:
  deadline: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - staticcheck
    - revive
    - deadcode
    - gosimple
    - ineffassign
    - unused
    - goconst
    - gocritic
    - godot
    - misspell
    - nlreturn
    - noctx
    - whitespace
    - varcheck

issues:
  exclude-use-default: false
