FROM quay.io/coreos/etcd:v3.5.5

RUN mkdir /certs
COPY ./scripts/tls/certs/* /certs/

EXPOSE 2389

CMD ["/usr/local/bin/etcd", "-advertise-client-urls", "https://xconf-etcds:2389", "-listen-client-urls", "https://0.0.0.0:2389", "-cert-file", "/certs/etcd_server_cert.pem", "-key-file", "/certs/etcd_server_key.pem"]
